kind = "web"
previewPath = "/"
title = "Boricua Web PR"
version = "1.0.0"
id = "artifacts/boricua-web-pr"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25843

[services.development]
run = "pnpm --filter @workspace/boricua-web-pr run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/boricua-web-pr", "run", "build" ]
publicDir = "artifacts/boricua-web-pr/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25843"
BASE_PATH = "/"
